name: dotnet

on: [push]

env:
  PROJECT_NAME: MinimalApi.Mediatr
  DOCKERFILE_PATH: artifacts/Dockerfile
  BUILD_CONFIGURATION: Release
  RUN_TESTS: false

jobs:
  dotnet:
    name: build and publish application
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: dotnet restore
        run: dotnet restore ${{ env.PROJECT_NAME }}.csproj
        working-directory: src/${{ env.PROJECT_NAME }}

      - name: dotnet test
        if: env.RUN_TESTS == 'true'
        run: dotnet test ${{ env.PROJECT_NAME }}.Tests.csproj  -c ${{ env.BUILD_CONFIGURATION }} --no-restore --verbosity normal
        working-directory: src/${{ env.PROJECT_NAME }}/Tests

      - name: dotnet build
        run: dotnet build ${{ env.PROJECT_NAME }}.csproj  --no-restore -c ${{ env.BUILD_CONFIGURATION }}
        working-directory: src/${{ env.PROJECT_NAME }}

      - name: dotnet publish
        run: dotnet publish ${{ env.PROJECT_NAME }}.csproj  --no-restore -c ${{ env.BUILD_CONFIGURATION }} --output ${{ env.ARTIFACTS_PATH }}/application
        working-directory: src/${{ env.PROJECT_NAME }}

      - name: publish application artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: src/${{ env.PROJECT_NAME }}/${{ env.ARTIFACTS_PATH }}/application
