name: dotnet

on: 
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      BUILD_CONFIGURATION:
        default: Release
        required: false
        type: string
      RUN_TEST:
        default: false
        required: false
        type: boolean

env:
  ARTIFACTS_PATH: application

jobs:
  dotnet:
    name: build and publish application
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: dotnet restore
        run: dotnet restore ${{ inputs.PROJECT_NAME }}.csproj
        working-directory: src/${{ inputs.PROJECT_NAME }}

      - name: dotnet test
        if: env.RUN_TESTS == 'true'
        run: dotnet test ${{ inputs.PROJECT_NAME }}.Tests.csproj  -c ${{ inputs.BUILD_CONFIGURATION }} --no-restore --verbosity normal
        working-directory: src/${{ inputs.PROJECT_NAME }}/Tests

      - name: dotnet build
        run: dotnet build ${{ inputs.PROJECT_NAME }}.csproj  --no-restore -c ${{ inputs.BUILD_CONFIGURATION }}
        working-directory: src/${{ inputs.PROJECT_NAME }}

      - name: dotnet publish
        run: dotnet publish ${{ inputs.PROJECT_NAME }}.csproj  --no-restore -c ${{ inputs.BUILD_CONFIGURATION }} --output /${{ env.ARTIFACTS_PATH }}
        working-directory: src/${{ inputs.PROJECT_NAME }}

      - name: publish application artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: src/${{ inputs.PROJECT_NAME }}/${{ env.ARTIFACTS_PATH }}/application
