name: angular

on: 
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      
jobs:
  angular:
    name: build and publish angular application
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout repo
        uses: actions/checkout@v2
            
      - name: install dependencies
        if:
          steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: angular build
        run: npm run build --prod
        working-directory: src
        
      - name: angular test
        run: npm run test
        working-directory: src      
             
      - name: publish application artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/${{ inputs.PROJECT_NAME }}




        
      
